create sequence CONFIG_IDX_SEQ;

INSERT INTO CONFIG (CONFIG_IDX, MODULE_IDX, TITLE, TITLE_OVERWRITE, INDEX_PAGE, LAYOUT_IDX, BASIC_SKIN, SKIN, STYLE_THEME) VALUES ('CONF000000000DEFAULT', 'MODUL000000000CONFIG', 'ainframe', 'Y', '/page/main', 'LAOUT00000000DEFAULT', 'tpl', 'basic', 'basic');
