CREATE SEQUENCE MENU_IDX_SEQ;

CREATE SEQUENCE MENU_TREE_IDX_SEQ;

insert into `MENU` (`MENU_NAME`, `REG_DATE`, `MENU_IDX`, `MOD_DATE`) values ('개발자', SYSDATE, 'MENU00000000000ADMIN', null);

insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('홈', 1, 'j1_1', 'menu', '/admin/module', '_self', 0, '/admin/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 1, null, 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('설정', 2, 'j1_2', 'j1_1', '/admin/config', '_self', 1, '/admin/config/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('모듈', 3, 'j1_3', 'j1_1', '/admin/module', '_self', 1, '/admin/module/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('레이아웃', 4, 'j1_4', 'j1_1', '/admin/layout', '_self', 1, '/admin/layout/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('메뉴', 5, 'j1_5', 'j1_1', '/admin/menu', '_self', 1, '/admin/menu/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('웹페이지', 6, 'j1_6', 'j1_1', '/admin/web_page', '_self', 1, '/admin/web_page/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('권한', 7, 'j1_7', 'j1_1', '/admin/grant/role', '_self', 1, '/admin/grant/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('회원', 8, 'j1_8', 'j1_1', '/admin/member', '_self', 1, '/admin/member/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('작업스케줄', 9, 'j1_9', 'j1_1', '/admin/crontab', '_self', 1, '/admin/crontab/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('포틀릿', 10, 'j1_10', 'j1_1', '/admin/portlet', '_self', 1, '/admin/portlet/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('페이지', 11, 'j1_11', 'j1_1', '/admin/page', '_self', 1, '/admin/page/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('컨텍스트', 12, 'j1_12', 'j1_1', '/admin/context', '_self', 1, '/admin/context/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');
insert into `MENU_TREE` (`TREE_NAME`, `TREE_ORDER`, `TREE_ID`, `PARENT_ID`, `URL`, `URL_WINDOW`, `TREE_DEPTH`, `URL_PATTERN`, `MENU_TREE_IDX`, `MENU_IDX`, `IMAGE_BASIC`, `IMAGE_OVER`, `IMAGE_SELECT`, `URL_TYPE`, `IS_MAIN_DISPLAY`, `PARENTS_ID`, `IS_TREE_MENU`, `TITLE_IMAGE`, `GROUP_ID`) values ('코드', 13, 'j1_13', 'j1_1', '/admin/code/group', '_self', 1, '/admin/code/**', 'MENUT' || LPAD(MENU_TREE_IDX_SEQ.NEXTVAL, 15, '0'), 'MENU00000000000ADMIN', null, null, null, 0, 0, 'j1_1', 0, null, 'j1_1');