create sequence MODULE_IDX_SEQ;
-- create sequence MODULE_OPTION_SRL_SEQ;

INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL000000000MODULE', 'module', 'module', '모듈', null, TO_DATE('2016-01-15 16:36:46', 'YYYY-MM-DD HH24:MI:SS'), null, 1);
