INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL000000000CONFIG', 'config', 'config', '설정', null, SYSDATE, null, 1);

INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL00000000000MENU', 'menu', 'menu', '메뉴', null, SYSDATE, null, 1);

INSERT INTO MODULE (MODULE_IDX, MODULE_NAME, MODULE_ID, BROWSER_TITLE, SKIN, REG_DATE, LAYOUT_IDX, USE_THEME) VALUES ('MODUL000000000LAYOUT', 'layout', 'layout', '레이아웃', null, SYSDATE, null, 1);