INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('attach_type', 'png|gif|bmp|jpg', null, 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('attach_total_size', '0', null, 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('attach_size', '0', null, 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('attach_limit', '2', null, 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('frontend_loading', null, null, 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('frontend_hash', 'e244188e9ef94722eabc', '프론트엔드 자원을 로드할때 사용되는 hash code', 'MODUL000000000CONFIG', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);

INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('max_depth', '4', '깊이', 'MODUL00000000000MENU', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);
INSERT INTO MODULE_OPTIONS(OPTIONS_NAME, OPTIONS_VALUE, OPTIONS_COMMENT, MODULE_IDX, MODULE_OPTIONS_SRL) VALUES ('max_children', '1', '최상위 자식수', 'MODUL00000000000MENU', MODULE_OPTIONS_SRL_SEQ.NEXTVAL);

